# Generated by Django 4.0.3 on 2022-10-11 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBankInformation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emp_bank', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bank', models.CharField(max_length=150)),
                ('bankBranch', models.CharField(max_length=150)),
                ('bankAccountNumber', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDependants',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emp_dependants', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(default='middle', max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=13)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='', max_length=6)),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('relationship', models.CharField(max_length=150)),
                ('residentialAddress', models.CharField(max_length=150)),
                ('identificationDocument', models.CharField(max_length=150)),
                ('identificationNumber', models.CharField(max_length=150)),
                ('taxNumber', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeIDInformation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emp_id', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('staffID', models.IntegerField(unique=True)),
                ('identificationDocument', models.CharField(max_length=150)),
                ('identificationNumber', models.CharField(max_length=150)),
                ('taxNumber', models.CharField(max_length=150)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMaritalInformation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emp_marital', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(default='middle', max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=13)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(max_length=150)),
                ('marriageDate', models.DateField(blank=True, null=True)),
                ('marriageCertificateNumber', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='', max_length=6)),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('residentialAddress', models.CharField(max_length=150)),
                ('identificationDocument', models.CharField(max_length=150)),
                ('identificationNumber', models.CharField(max_length=150)),
                ('taxNumber', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeNextOfKin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emp_kin', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('relationship', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(default='middle', max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=13)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='', max_length=6)),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('residentialAddress', models.CharField(max_length=150)),
                ('identificationDocument', models.CharField(max_length=150)),
                ('identificationNumber', models.CharField(max_length=150)),
                ('taxNumber', models.CharField(max_length=150)),
            ],
        ),
    ]
