# Generated by Django 4.0.3 on 2022-10-11 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employeebankinformation_employeedependants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeebankinformation',
            old_name='user',
            new_name='staffID',
        ),
        migrations.RenameField(
            model_name='employeedependants',
            old_name='user',
            new_name='staffID',
        ),
        migrations.RenameField(
            model_name='employeemaritalinformation',
            old_name='user',
            new_name='staffID',
        ),
        migrations.RenameField(
            model_name='employeenextofkin',
            old_name='user',
            new_name='staffID',
        ),
        migrations.RemoveField(
            model_name='employeeidinformation',
            name='user',
        ),
        migrations.AlterField(
            model_name='employeeidinformation',
            name='staffID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emp_id', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
