# Generated by Django 4.0.3 on 2022-10-11 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_employeebankinformation_staffid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeidinformation',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeidinformation',
            name='startDate',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
