# Generated by Django 4.0.3 on 2022-10-11 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employeeidinformation_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeidinformation',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
