# Generated by Django 4.0.3 on 2022-10-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employeeidinformation_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedependants',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employeemaritalinformation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employeenextofkin',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
