# Generated by Django 4.0.3 on 2022-10-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_employeedependants_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedependants',
            name='middle_name',
            field=models.CharField(default='Middle', max_length=150),
        ),
        migrations.AlterField(
            model_name='employeemaritalinformation',
            name='middle_name',
            field=models.CharField(default='Middle', max_length=150),
        ),
        migrations.AlterField(
            model_name='employeenextofkin',
            name='middle_name',
            field=models.CharField(default='Middle', max_length=150),
        ),
    ]
