# Generated by Django 4.0.3 on 2022-10-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_staffid_employeebankinformation_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeebankinformation',
            old_name='user',
            new_name='staffID',
        ),
        migrations.RenameField(
            model_name='employeedependants',
            old_name='user',
            new_name='staffID',
        ),
        migrations.RenameField(
            model_name='employeeidinformation',
            old_name='user',
            new_name='staffID',
        ),
        migrations.RenameField(
            model_name='employeemaritalinformation',
            old_name='user',
            new_name='staffID',
        ),
        migrations.RenameField(
            model_name='employeenextofkin',
            old_name='user',
            new_name='staffID',
        ),
    ]
