# Generated by Django 3.2.5 on 2021-07-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Activity Description', max_length=155)),
                ('description', models.CharField(default='Activity Details', max_length=300)),
                ('slug', models.SlugField(default='slug', max_length=250, unique_for_date='date_created')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Work in progress', 'Work in progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Created', max_length=30)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Official', 'Official')], default='', max_length=155)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
