# Generated by Django 3.2 on 2021-04-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitys', '0001_initial'),
    ]

    operations = [
    ]
