# Generated by Django 3.2 on 2021-05-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitys', '0002_auto_20210428_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(default='slug', max_length=250, unique_for_date='date_created'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('PS', 'Created'), ('WIP', 'Work in progress'), ('CC', 'Completed'), ('CS', 'Closed')], default='Created', max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activitys', to='activitys.activitycategory'),
        ),
    ]
