# Generated by Django 3.2.5 on 2021-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitys', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(default='Activity Details', max_length=132),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(default='Activity Description', max_length=32),
        ),
    ]
