# Generated by Django 3.2 on 2021-05-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitys', '0004_auto_20210505_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitycategory',
            old_name='styles',
            new_name='style',
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='linenos',
            field=models.BooleanField(default=False),
        ),
    ]
