# Generated by Django 3.2 on 2021-05-08 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activitys', '0005_auto_20210505_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycategory',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='activitycategory',
            name='language',
        ),
        migrations.RemoveField(
            model_name='activitycategory',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='activitycategory',
            name='style',
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activityscategorys', to=settings.AUTH_USER_MODEL),
        ),
    ]
