# Generated by Django 3.2.6 on 2022-01-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLAccountBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentDate', models.DateField(auto_now_add=True)),
                ('localCurrency', models.CharField(choices=[('KSH', 'KSH'), ('UGX', 'UGX'), ('TZS', 'TZS'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3)),
                ('fiscalYear', models.IntegerField()),
                ('ledger', models.CharField(max_length=2, unique=True)),
                ('postingPeriod', models.IntegerField(unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('openingBalance', models.DecimalField(decimal_places=2, max_digits=17)),
                ('periodDebit', models.DecimalField(decimal_places=2, max_digits=17)),
                ('periodCredit', models.DecimalField(decimal_places=2, max_digits=17)),
                ('closingBalance', models.DecimalField(decimal_places=2, max_digits=17)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateChanged', models.DateTimeField(auto_now=True)),
                ('accountNumber', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.PROTECT, related_name='accountNumber_GLAccountBalances', to='masterdata.generalledgeaccountmaster')),
                ('companyCode', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.PROTECT, related_name='companyCode_GLAccountBalances', to='company.companycode')),
                ('glLongDescription', models.ForeignKey(max_length=135, on_delete=django.db.models.deletion.PROTECT, related_name='glLongDescription_GLAccountBalances', to='masterdata.generalledgeaccountmaster')),
            ],
            options={
                'ordering': ('accountNumber',),
            },
        ),
    ]
