# Generated by Django 4.0.3 on 2022-08-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_generalledgeraccountmaster_and_more'),
        ('accountbalances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaccountbalances',
            name='accountNumber',
            field=models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.PROTECT, related_name='accountNumber_GLAccountBalances', to='masterdata.generalledgeraccountmaster'),
        ),
        migrations.AlterField(
            model_name='glaccountbalances',
            name='glLongDescription',
            field=models.ForeignKey(max_length=135, on_delete=django.db.models.deletion.PROTECT, related_name='glLongDescription_GLAccountBalances', to='masterdata.generalledgeraccountmaster'),
        ),
    ]
