version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
    - 8000:8000
    depends_on:
      - db
  db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes: 
      #- .:/code
      - onlineshop-volume:/var/lib/postgresql/data
volumes:
  onlineshop-volume:
  