# Generated by Django 3.2.6 on 2022-01-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.IntegerField(unique=True)),
                ('documentDate', models.DateField()),
                ('postingDate', models.DateField()),
                ('reference', models.CharField(max_length=50)),
                ('headerText', models.CharField(max_length=50)),
                ('shortDescription', models.CharField(max_length=50)),
                ('dr', models.CharField(choices=[('DR', 'DR'), ('CR', 'CR')], max_length=6)),
                ('cr', models.CharField(choices=[('DR', 'DR'), ('CR', 'CR')], max_length=6)),
                ('currency', models.CharField(choices=[('KSH', 'KSH'), ('UGX', 'UGX'), ('TZS', 'TZS'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=35)),
                ('amountInDocumentCurrency', models.DecimalField(decimal_places=2, max_digits=17)),
                ('taxAmountInDocumentCurrency', models.DecimalField(decimal_places=2, max_digits=17)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateChanged', models.DateTimeField(auto_now=True)),
                ('accountNumber', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.PROTECT, related_name='accountNumber_GLDocument', to='masterdata.generalledgeaccountmaster')),
                ('companyCode', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.PROTECT, related_name='companyCode_GLDocument', to='company.companycode')),
                ('taxCode', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.PROTECT, related_name='taxCode_GLDocument', to='masterdata.taxcode')),
            ],
            options={
                'ordering': ('accountNumber',),
            },
        ),
        migrations.CreateModel(
            name='GLAccountLineItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.IntegerField(unique=True)),
                ('documentType', models.CharField(max_length=2)),
                ('documentDate', models.DateField()),
                ('localCurrency', models.CharField(choices=[('KSH', 'KSH'), ('UGX', 'UGX'), ('TZS', 'TZS'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3)),
                ('amountInLocalCurrency', models.DecimalField(decimal_places=2, max_digits=17)),
                ('taxCode', models.CharField(max_length=2)),
                ('taxAmountLocalCurrency', models.DecimalField(decimal_places=2, max_digits=17)),
                ('amountInForeignCurrency', models.DecimalField(decimal_places=2, max_digits=17)),
                ('taxAmountForeignCurrency', models.DecimalField(decimal_places=2, max_digits=17)),
                ('clearingDocument', models.CharField(max_length=10)),
                ('documentText', models.CharField(max_length=135)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateChanged', models.DateTimeField(auto_now=True)),
                ('accountNumber', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.PROTECT, related_name='accountNumber_GLAccountLineItems', to='masterdata.generalledgeaccountmaster')),
                ('companyCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyCode_GLAccountLineItems', to='company.companycode')),
            ],
        ),
    ]
