# Generated by Django 3.2.6 on 2022-01-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxCode', models.CharField(max_length=2, unique=True)),
                ('taxCodeDescription', models.CharField(max_length=50)),
                ('taxCodePercentage', models.DecimalField(decimal_places=2, max_digits=17, unique=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateChanged', models.DateTimeField(auto_now=True)),
                ('companyCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyCode_TaxCode', to='company.companycode')),
            ],
            options={
                'ordering': ('taxCode',),
            },
        ),
        migrations.CreateModel(
            name='GLAccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountGroup', models.CharField(max_length=4, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('fromAccount', models.IntegerField(unique=True)),
                ('toAccount', models.IntegerField(unique=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateChanged', models.DateTimeField(auto_now=True)),
                ('chartOfAccounts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='glAccountGroup', to='company.chartofaccounts')),
                ('companyCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyCode_GLAccountGroup', to='company.companycode')),
            ],
            options={
                'ordering': ('chartOfAccounts',),
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgeAccountMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.IntegerField(unique=True)),
                ('profitAndLossAccount', models.BooleanField()),
                ('balanceSheetAccount', models.BooleanField()),
                ('shortDescription', models.CharField(max_length=50)),
                ('longDescription', models.CharField(max_length=135)),
                ('accountCurrency', models.CharField(choices=[('KSH', 'KSH'), ('UGX', 'UGX'), ('TZS', 'TZS'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3)),
                ('balancesLocalCurrency', models.BooleanField()),
                ('exchangeRateDiffKey', models.CharField(max_length=3)),
                ('taxCategory', models.CharField(max_length=2)),
                ('taxableItem', models.BooleanField()),
                ('reconciliationAccountType', models.CharField(choices=[('Assets', 'Assets'), ('Accounts Payables', 'Accounts Payable'), ('Accounts Receivables', 'Accounts Receivable'), ('Materials', 'Materials'), ('None', 'None')], max_length=30)),
                ('openItemMgt', models.BooleanField()),
                ('lineItemDisplay', models.BooleanField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateChanged', models.DateTimeField(auto_now=True)),
                ('companyCode', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgeAccountMaster', to='company.companycode')),
                ('glAccountGroup', models.ForeignKey(blank=True, max_length=4, on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgeAccountMaster', to='masterdata.glaccountgroup')),
            ],
            options={
                'ordering': ('accountNumber',),
            },
        ),
    ]
