# Generated by Django 4.0.3 on 2022-08-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_alter_taxcode_taxcodepercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerAccountMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.IntegerField(unique=True)),
                ('accountType', models.CharField(choices=[('Assets', 'Assets'), ('Accounts Payables', 'Accounts Payable'), ('Accounts Receivables', 'Accounts Receivable'), ('Materials', 'Materials')], max_length=30)),
                ('reconciliationAccountInput', models.BooleanField()),
                ('reconciliationAccountType', models.CharField(choices=[('Assets', 'Assets'), ('Accounts Payables', 'Accounts Payable'), ('Accounts Receivables', 'Accounts Receivable'), ('Materials', 'Materials'), ('None', 'None')], max_length=30)),
                ('alternativeGLAccount', models.IntegerField(unique=True)),
                ('shortDescription', models.CharField(max_length=50)),
                ('longDescription', models.CharField(max_length=135)),
                ('profitAndLossAccount', models.BooleanField()),
                ('balanceSheetAccount', models.BooleanField()),
                ('accountCurrency', models.CharField(choices=[('KSH', 'KSH'), ('UGX', 'UGX'), ('TZS', 'TZS'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3)),
                ('balancesInLocalCurrency', models.BooleanField()),
                ('exchangeRateKey', models.CharField(max_length=3)),
                ('taxCategory', models.CharField(max_length=2)),
                ('postingWithoutTaxAllowed', models.BooleanField()),
                ('openItemManagement', models.BooleanField()),
                ('lineItemManagement', models.BooleanField()),
                ('blockedForPosting', models.BooleanField()),
                ('markedForDeletion', models.BooleanField()),
                ('groupAccountNumber', models.IntegerField(unique=True)),
                ('tradingPartner', models.IntegerField()),
                ('sortKey', models.CharField(max_length=2)),
                ('authorizationGroup', models.CharField(max_length=4)),
                ('fieldStatusGroup', models.CharField(max_length=4)),
                ('postAutomaticallyOnly', models.BooleanField()),
                ('relevantToCashFlow', models.BooleanField()),
                ('houseBank', models.CharField(max_length=4)),
                ('houseBankAccountID', models.IntegerField(unique=True)),
                ('interestIndicator', models.BooleanField()),
                ('interestCalculationFrequency', models.IntegerField(unique=True)),
                ('lastDateOfInterestCalculation', models.DateField()),
                ('keyDateofLastInterest', models.DateField()),
                ('costElement', models.IntegerField(unique=True)),
                ('unitOfMeasure', models.CharField(max_length=5)),
                ('valuationGroup', models.CharField(max_length=5)),
                ('inflationKey', models.CharField(max_length=2)),
                ('toleranceGroup', models.CharField(max_length=5)),
                ('planningLevel', models.CharField(max_length=2)),
                ('accountManagedinExternalSystem', models.BooleanField()),
                ('supplementAutomaticPostings', models.BooleanField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateChanged', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('accountNumber',),
            },
        ),
        migrations.RemoveField(
            model_name='generalledgeaccountmaster',
            name='companyCode',
        ),
        migrations.RemoveField(
            model_name='generalledgeaccountmaster',
            name='glAccountGroup',
        ),
        migrations.RemoveField(
            model_name='glaccountgroup',
            name='fromAccount',
        ),
        migrations.RemoveField(
            model_name='glaccountgroup',
            name='toAccount',
        ),
    ]
