# Generated by Django 4.0.3 on 2022-08-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountitems', '0002_alter_glaccountlineitems_accountnumber_and_more'),
        ('masterdata', '0003_generalledgeraccountmaster_and_more'),
        ('company', '0002_alter_companycode_options_and_more'),
        ('accountbalances', '0002_alter_glaccountbalances_accountnumber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralLedgeAccountMaster',
        ),
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='accountGroup',
            field=models.ForeignKey(blank=True, max_length=4, on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgerAccountMaster', to='masterdata.glaccountgroup'),
        ),
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='businessArea',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgeAccountMaster', to='company.businessarea'),
        ),
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='chartOfAccounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgerAccountMaster', to='company.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='companyCode',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgerAccountMaster', to='company.companycode'),
        ),
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='controllingArea',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgeAccountMaster', to='company.controllingarea'),
        ),
    ]
