# Generated by Django 4.0.3 on 2022-09-09 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_chartofaccounts_language_and_more'),
        ('masterdata', '0004_delete_generalledgeaccountmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='businessArea',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgerAccountMaster', to='company.businessarea'),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='controllingArea',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgerAccountMaster', to='company.controllingarea'),
        ),
        migrations.CreateModel(
            name='GeneralLedgerAccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountGroup', models.CharField(max_length=4, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateChanged', models.DateTimeField(auto_now=True)),
                ('chartOfAccounts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgerAccountGroup', to='company.chartofaccounts')),
                ('companyCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgerAccountGroup', to='company.companycode')),
            ],
            options={
                'ordering': ('chartOfAccounts',),
            },
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='accountGroup',
            field=models.ForeignKey(blank=True, max_length=4, on_delete=django.db.models.deletion.PROTECT, related_name='GeneralLedgerAccountMaster', to='masterdata.generalledgeraccountgroup'),
        ),
        migrations.DeleteModel(
            name='GLAccountGroup',
        ),
    ]
