# Generated by Django 4.0.3 on 2023-03-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_alter_generalledgeraccountmaster_accounttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='accountGroup',
            field=models.CharField(max_length=4),
        ),
    ]
