# Generated by Django 4.0.3 on 2024-01-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_alter_generalledgeraccountmaster_accountgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='exchangeRateKey',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='sortKey',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='taxCategory',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
