# Generated by Django 4.0.3 on 2024-01-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_alter_generalledgeraccountmaster_exchangeratekey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledgeraccountmaster',
            name='interestCalculationFrequency',
        ),
        migrations.RemoveField(
            model_name='generalledgeraccountmaster',
            name='interestIndicator',
        ),
        migrations.RemoveField(
            model_name='generalledgeraccountmaster',
            name='keyDateofLastInterest',
        ),
        migrations.RemoveField(
            model_name='generalledgeraccountmaster',
            name='lastDateOfInterestCalculation',
        ),
    ]
