# Generated by Django 4.0.3 on 2024-02-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_remove_generalledgeraccountmaster_accountmanagedinexternalsystem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='accountManagedinExternalSystem',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='inflationKey',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='planningLevel',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='supplementAutomaticPostings',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='unitOfMeasure',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='valuationGroup',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
