# Generated by Django 4.0.3 on 2024-02-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_generalledgeraccountmaster_accountmanagedinexternalsystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='accountManagedinExternalSystem',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='balanceSheetAccount',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='balancesInLocalCurrency',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='blockedForPosting',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='lineItemManagement',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='markedForDeletion',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='openItemManagement',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='postAutomaticallyOnly',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='postingWithoutTaxAllowed',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='profitAndLossAccount',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='reconciliationAccountInput',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='relevantToCashFlow',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='supplementAutomaticPostings',
            field=models.BooleanField(blank=True),
        ),
    ]
