# Generated by Django 4.0.3 on 2024-03-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_alter_generalledgeraccountmaster_accountmanagedinexternalsystem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledgeraccountmaster',
            name='balanceSheetAccount',
        ),
        migrations.RemoveField(
            model_name='generalledgeraccountmaster',
            name='profitAndLossAccount',
        ),
        migrations.AddField(
            model_name='generalledgeraccountmaster',
            name='financialStatementAccount',
            field=models.CharField(choices=[('Profit and Loss Account', 'Profit and Loss Account'), ('Balance Sheet Account', 'Balance Sheet Account')], default='Balance Sheet Account', max_length=30),
        ),
    ]
