# Generated by Django 4.0.3 on 2024-03-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_remove_generalledgeraccountmaster_balancesheetaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='tradingPartner',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
