# Generated by Django 4.0.3 on 2024-04-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0021_alter_generalledgeraccountmaster_accountmanagedinexternalsystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='reconciliationAccountType',
            field=models.CharField(blank=True, choices=[('Assets', 'Assets'), ('Accounts Payables', 'Accounts Payable'), ('Accounts Receivables', 'Accounts Receivable'), ('Materials', 'Materials'), ('General Ledger', 'General Ledger')], max_length=30),
        ),
    ]
