# Generated by Django 4.0.3 on 2024-05-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0023_alter_generalledgeraccountmaster_alternativeglaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='costElement',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='groupAccountNumber',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='generalledgeraccountmaster',
            name='houseBankAccountID',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
