# Generated by Django 3.1.7 on 2021-04-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(default='Task Description', max_length=155)),
                ('details', models.CharField(default='Task Details', max_length=300)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
