# Generated by Django 3.2.6 on 2022-01-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=4, unique=True)),
                ('companyName', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('postOfficeBox', models.IntegerField(default=12345, null=True)),
                ('postalCode', models.IntegerField(default=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(choices=[('English', 'en'), ('English', 'fr'), ('English', 'es'), ('English', 'de')], default='en', max_length=35)),
                ('currency', models.CharField(choices=[('KSH', 'KSH'), ('UGX', 'UGX'), ('TZS', 'TZS'), ('USD', 'USD'), ('GBP', 'GBP')], default='KSH', max_length=3)),
                ('landLine', models.IntegerField(blank=True, null=True)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateChanged', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('company',),
            },
        ),
        migrations.CreateModel(
            name='ReportingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=50)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateChanged', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyCode', to='company.company')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ChartOfaccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coaCode', models.CharField(max_length=4, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('English', 'en'), ('English', 'fr'), ('English', 'es'), ('English', 'de')], default='en', max_length=35)),
                ('lengthGlAccNumber', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateChanged', models.DateTimeField(auto_now=True)),
                ('companyCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyCode_ChartOfaccounts', to='company.companycode')),
            ],
            options={
                'ordering': ('coaCode',),
            },
        ),
    ]
