# Generated by Django 4.0.3 on 2022-08-04 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycode',
            options={'ordering': ('companyCode',)},
        ),
        migrations.AlterModelOptions(
            name='reportingarea',
            options={'ordering': ('reportingArea',)},
        ),
        migrations.RenameField(
            model_name='chartofaccounts',
            old_name='description',
            new_name='chartOfAccountsName',
        ),
        migrations.RenameField(
            model_name='chartofaccounts',
            old_name='lengthGlAccNumber',
            new_name='lengthAccNumber',
        ),
        migrations.RenameField(
            model_name='companycode',
            old_name='code',
            new_name='companyCode',
        ),
        migrations.RenameField(
            model_name='companycode',
            old_name='description',
            new_name='companyCodeName',
        ),
        migrations.AddField(
            model_name='reportingarea',
            name='chartOfAccounts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='ReportingArea', to='company.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='reportingarea',
            name='companyCode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='ReportingArea', to='company.companycode'),
        ),
        migrations.AddField(
            model_name='reportingarea',
            name='dateChanged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reportingarea',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reportingarea',
            name='personResponsible',
            field=models.CharField(default='', max_length=135),
        ),
        migrations.AddField(
            model_name='reportingarea',
            name='reportingArea',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='reportingarea',
            name='reportingAreaName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='companyCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ChartOfaccounts', to='company.companycode'),
        ),
        migrations.AlterField(
            model_name='companycode',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CompanyCode', to='company.company'),
        ),
        migrations.CreateModel(
            name='ControllingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controllingArea', models.CharField(default='', max_length=4, unique=True)),
                ('controllingAreaName', models.CharField(default='', max_length=50)),
                ('personResponsible', models.CharField(default='', max_length=135)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateChanged', models.DateTimeField(default=django.utils.timezone.now)),
                ('chartOfAccounts', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='ControllingArea', to='company.chartofaccounts')),
                ('companyCode', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='ControllingArea', to='company.companycode')),
            ],
            options={
                'ordering': ('controllingArea',),
            },
        ),
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessArea', models.CharField(default='', max_length=4, unique=True)),
                ('businessAreaName', models.CharField(default='', max_length=50)),
                ('personResponsible', models.CharField(default='', max_length=135)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateChanged', models.DateTimeField(default=django.utils.timezone.now)),
                ('chartOfAccounts', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='BusinessArea', to='company.chartofaccounts')),
                ('companyCode', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='BusinessArea', to='company.companycode')),
            ],
            options={
                'ordering': ('businessArea',),
            },
        ),
    ]
