# Generated by Django 4.0.3 on 2022-09-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companycode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('swa', 'swa'), ('fr', 'fr'), ('es', 'es'), ('de', 'de')], default='en', max_length=35),
        ),
        migrations.AlterField(
            model_name='company',
            name='dateChanged',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('swa', 'swa'), ('fr', 'fr'), ('es', 'es'), ('de', 'de')], default='en', max_length=35),
        ),
    ]
