# Generated by Django 4.0.3 on 2022-09-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_chartofaccounts_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartofaccounts',
            old_name='status',
            new_name='blockedForPosting',
        ),
        migrations.RemoveField(
            model_name='businessarea',
            name='chartOfAccounts',
        ),
        migrations.RemoveField(
            model_name='controllingarea',
            name='chartOfAccounts',
        ),
        migrations.RemoveField(
            model_name='reportingarea',
            name='chartOfAccounts',
        ),
    ]
